version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: Postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data     
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432   
    volumes:
      - ./data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  adminer:
    image: adminer
    restart: always
    ports:
      - ${WEB_PORT}:8080
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"
